### ISSUE TITLE
Unmounting when zoom level is less than some layer's minZoom causes error

### ISSUE THREAD

**Issue by tkurki** [PaulLeCam/react-leaflet#625] opened 2019-10-02 20:16 UTC
## Bug report in v2

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v16.3.0 minimum).
- [] Using the supported version of Leaflet (v1.4.x) and its corresponding CSS file is loaded. **1.5.1, like the Codepen and what yarn add leaflet brought in**
- [x] Using the [latest version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases) - **not v1.x**.
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/en/intro.html) and that you understand the [limitations](https://react-leaflet.js.org/docs/en/intro.html#limitations).

### Expected behavior

`Map` is unmounted without errors.

### Actual behavior

Leaflet throws an error and UI crashes.
```
Uncaught TypeError: Cannot read property 'style' of undefined
    at xi (leaflet.js:5)
    at i.<anonymous> (leaflet.js:5)
    at i.fire (leaflet.js:5)
    at i._moveEnd (leaflet.js:5)
    at i._resetView (leaflet.js:5)
    at i.setView (leaflet.js:5)
    at i.setZoom (leaflet.js:5)
    at i._updateZoomLevels (leaflet.js:5)
    at i._removeZoomLimit (leaflet.js:5)
    at i.onRemove (leaflet.js:5)
```

### Steps to reproduce

https://codepen.io/tkurki/pen/GRKVzgZ?editors=0011
The map first zooms out to level 9, then starts again at 13 and unmounts at zoom level 10.

**Comment by PaulLeCam** [comment] 2019-10-15 02:51
As the React warning is stating, you're updating state on an unmounted component, so my guess is that this is related.
Please address the warning and let me know if the problem persists.

**Comment by tkurki** [comment] 2019-10-19 09:31
The React warning comes *after* the error that I included in the description above.

But as the React warning is unrelated noise I created a less convoluted codepen that does not try to keep going after the error: https://codepen.io/tkurki/pen/zYYoBbZ

The example
- shows and hides a `LeafletMap` with zoom level 13 successfully
- shows and tries to hide the same `LeafletMap` with zoom level 9

Please **see browser's js console**, not Codepen console:
![image](https://user-images.githubusercontent.com/1049678/67142138-0f624900-f26c-11e9-92b4-a673cc5bd24b.png)

**Comment by PaulLeCam** [comment] 2019-10-20 05:35
It seems to be caused by Leaflet's logic updating the zoom constraints on the map as the tile layer is removed, but it fails because the map is removed as well.
I can't think of a simple workaround that could be applied in React Leaflet as it's part of Leaflet's internal logic, but if you have one please open a PR.

**Comment by tkurki** [comment] 2019-10-20 15:41
This is actually a Leaflet bug, see the referenced issue. Feel free to close this issue or keep it open as a known bug. Maybe tag it as a `Bug in Leaflet`, so that it can be revisited when you get new Leaflet versions?

In React you can work around it with an [Error Boundary](https://reactjs.org/docs/error-boundaries.html).

**Comment by PaulLeCam** [comment] 2019-11-18 10:57
Closing as it's caused by Leaflet.

**Closed by PaulLeCam** 2019-11-18 10:57 UTC
