### ISSUE TITLE
Can't compile react-leaflet

### ISSUE THREAD

**Issue by pkdhital** [PaulLeCam/react-leaflet#891] opened 2021-06-06 04:15 UTC
## Bug report

Can't compile blank react app after adding react-leaflet. Throws following error:
`
>./node_modules/@react-leaflet/core/esm/path.js 10:41
>Module parse failed: Unexpected token (10:41)
>File was processed with these loaders:
 >* ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
>You may need an additional loader to handle the result of these loaders.
>|   useEffect(function updatePathOptions() {
>|     if (props.pathOptions !== optionsRef.current) {
>       const options = props.pathOptions ?? {};
>|       element.instance.setStyle(options);
>|       optionsRef.current = options;

`
### Expected behavior

Should compile and be able to use react leaflet

### Steps to reproduce

>npx create-react-app test
>cd test
>npm install leaflet react-leaflet
add  `import { MapContainer, TileLayer, Marker, Popup } from 'react-leaflet'` on src/App.js
>npm start

## Edit
For me https://github.com/PaulLeCam/react-leaflet/issues/891#issuecomment-860152169 this resolved issue, but comments below indicate it's not working for everybody. Please try this and check if it's working for you or not.

**Comment by MGraefe** [comment] 2021-06-07 15:26
Having the same issue, related thread in create-react-app:

https://github.com/facebook/create-react-app/issues/9468#issuecomment-694191642

Picked up a lot of activity in the last ~20 days. See last comments for remarks from react guys.

**Comment by vyemialyanchyk** [comment] 2021-06-11 18:37
{code}
./node_modules/@react-leaflet/core/esm/path.js 10:41
Module parse failed: Unexpected token (10:41)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   useEffect(function updatePathOptions() {
|     if (props.pathOptions !== optionsRef.current) {
>       const options = props.pathOptions ?? {};
|       element.instance.setStyle(options);
|       optionsRef.current = options;
{code}
 the same issue

**Comment by vyemialyanchyk** [comment] 2021-06-11 18:49
`Failed to compile.

./node_modules/@react-leaflet/core/esm/pane.js 2:27
Module parse failed: Unexpected token (2:27)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| export function withPane(props, context) {
>   const pane = props.pane ?? context.pane;
|   return pane ? { ...props,
|     pane`

**Comment by vyemialyanchyk** [comment] 2021-06-11 18:52
`Failed to compile.

./node_modules/@react-leaflet/core/esm/layer.js 8:46
Module parse failed: Unexpected token (8:46)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| export function useLayerLifecycle(element, context) {
|   useEffect(function addLayer() {
>     const container = context.layerContainer ?? context.map;
|     container.addLayer(element.instance);
|     return function removeLayer() {

`

**Comment by vyemialyanchyk** [comment] 2021-06-11 19:08
`Failed to compile.

./node_modules/react-leaflet/esm/Pane.js 25:37
Module parse failed: Unexpected token (25:37)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   }
|
>   const parentPaneName = props.pane ?? context.pane;
|   const parentPane = parentPaneName ? context.map.getPane(parentPaneName) : undefined;
|   const element = context.map.createPane(name, parentPane);


`

**Comment by vyemialyanchyk** [comment] 2021-06-11 19:11
`Failed to compile.

./node_modules/react-leaflet/esm/MapContainer.js 72:30
Module parse failed: Unexpected token (72:30)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   const contents = context ? /*#__PURE__*/React.createElement(LeafletProvider, {
|     value: context
>   }, children) : placeholder ?? null;
|   return /*#__PURE__*/React.createElement("div", _extends({}, props, {
|     ref: mapRef


`

**Comment by vyemialyanchyk** [comment] 2021-06-11 19:13
I assume this is can be treated as critical..

**Comment by lukasa1993** [comment] 2021-06-12 07:05
how this is not fixed asap ?

**Comment by tanmaster** [comment] 2021-06-12 11:42
Same issue...

**Comment by miha42-github** [comment] 2021-06-12 16:43
Exactly the same problem.  This seems to be a problem that keeps on giving in some form or fashion without a consistent resolution.

**Comment by phosphene47** [comment] 2021-06-13 02:33
This issue can be reproduced with next.js as well.

```
info  - Checking validity of types...
info  - Creating an optimized production build...
info  - Using external babel configuration from /app/babel.config.js
Failed to compile.

./node_modules/@react-leaflet/core/esm/path.js
Module parse failed: Unexpected token (10:41)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   useEffect(function updatePathOptions() {
|     if (props.pathOptions !== optionsRef.current) {
>       const options = props.pathOptions ?? {};
|       element.instance.setStyle(options);
|       optionsRef.current = options;


> Build error occurred
Error: > Build failed because of webpack errors
    at /app/node_modules/next/dist/build/index.js:17:924
    at async Span.traceAsyncFn (/app/node_modules/next/dist/telemetry/trace/trace.js:6:584)
error Command failed with exit code 1.
```

**Comment by pkdhital** [comment] 2021-06-13 05:07
Ok somewhere else in internet, I found following fix:

1. Go to package.json and find following segment
`
"browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
`
2. And replace it with following

`"browserslist": [
    ">0.2%",
    "not dead",
    "not op_mini all"
  ]
`
3. Remove packahe-lock.json file
4. Run project again it should compile.

**Comment by designbyadrian** [comment] 2021-06-13 05:08
This doesn't resolve the issue, and also isn't working for everybody. Don't close this ticket!

**Comment by MGraefe** [comment] 2021-06-13 08:07
Changing the browser target is a stupid workaround but not a fix. It's also not necessary for any of the other probably thousand packages in a typical project.

**Comment by ilindaniel** [comment] 2021-06-13 14:50
This has already been addressed here:
https://github.com/PaulLeCam/react-leaflet/issues/877#issuecomment-858199065
https://github.com/PaulLeCam/react-leaflet/issues/881#issuecomment-858346012

A quick fix is to downgrade Leaflet. In your package.json file, change these lines:
```
"react-leaflet": ">=3.1.0 <3.2.0 || ^3.2.1",
"@react-leaflet/core": ">=1.0.0 <1.1.0 || ^1.1.1"
```

Then remove the node_modules folder and run `npm install`.

Optional: `npm install --save @monsonjeremy/react-leaflet`
See: https://github.com/facebook/create-react-app/issues/9468#issuecomment-694191642
Use at your own risk though, as the author will not be further maintaining this package. It is only to hold over until his PR gets merged.

**Comment by vyemialyanchyk** [comment] 2021-06-14 23:29
'??' should be replaced with ':?' in 5 places which I posted above for quickfix.

**Comment by dennisat** [comment] 2021-06-17 06:57
Com' on, it's only one line _hope so_ , why nobody fixing this?

**Comment by mattstrain** [comment] 2021-06-17 19:43
Same issue trying to import vis-data.

```/Code/react/monorepo/node_modules/vis-data/esnext/esm/vis-data.js 1437:21
Module parse failed: Unexpected token (1437:21)
File was processed with these loaders:
 * ../../node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|       if (id != null) {
|         // a single item
>         return item ?? null;
|       } else {
|         // just return our array
```

**Comment by daniofilho** [comment] 2021-06-21 13:42
I fixed this upgrading to webpack 5, if it helps somebody.

**Comment by adeelibr** [comment] 2021-06-29 11:50
any update on this issue? using create-react-app

**Comment by dennisat** [comment] 2021-06-29 12:51
## No clean solution so far

But this workaround works for me without eject!

1. Use the `react-app-rewired`, read the doc how to add it
2. Create a `config-overrides.js` at root with this content

```
const {
  override,
  addExternalBabelPlugins,
} = require("customize-cra");

module.exports = {
  webpack: override(
    ...addExternalBabelPlugins(
      "@babel/plugin-proposal-nullish-coalescing-operator"
    ),
  ),
};

```

**Comment by mscandan** [comment] 2021-07-03 13:46
this [answer](https://github.com/PaulLeCam/react-leaflet/issues/891#issuecomment-860152169) worked for me

**Comment by oasis1992** [comment] 2021-07-05 02:04
> "react-leaflet": ">=3.1.0 <3.2.0 || ^3.2.1",
> "@react-leaflet/core": ">=1.0.0 <1.1.0 || ^1.1.1"

this solution is the fastest

**Comment by DVGY** [comment] 2021-07-26 04:37
Hey guys i am also facing this issue

**Comment by designbyadrian** [comment] 2021-07-28 07:44
@DVGY 

Please use the +1 icon (👍) at the top of the issue instead of writing "me too". Repo owners can find popular tickets that way. Comments are made for discussing the issue.

**Comment by alteyss** [comment] 2021-09-02 15:40
Hi 🙂

In my case I had to use a webpack rule with the following packages as quoted above : 

> "react-leaflet": ">=3.1.0 <3.2.0 || ^3.2.1",
> "@react-leaflet/core": ">=1.0.0 <1.1.0 || ^1.1.1"

```
config.module.rules.push(
    {
        test: /\.m?js$/,
        include: [/node_modules\/react-leaflet/],
        use: {
            loader: 'babel-loader',
            options: {
                plugins: [
                    '@babel/plugin-proposal-optional-chaining',
                    '@babel/plugin-proposal-nullish-coalescing-operator'
                ]
            }
        }
    }
);
```

As you can see, I only include react-leaflet that was causing trouble. 

Context : PWA Studio (based on React).

**Comment by jayarjo** [comment] 2021-09-04 17:11
Fix this please. It's ridiculous.

**Comment by limal** [comment] 2021-09-21 20:37
For **Next.js 11** do two following things:

1. In `next.config.js` specifically target the `@react-leaflet/core` inside the `node_modules` like below. Otherwise it won't transpile the offending module.

```javascript
 const withTM = require("next-transpile-modules")([
  "react-leaflet/node_modules/@react-leaflet/core", // specifying just the "react-leaflet" won't work
]);
```

2. To avoid the `window` is not defined import your `Map` component dynamically with the SSR turned off:

```
const DynamicMap = dynamic(() => import("../../src/components/map/Map"), { ssr: false });

const MapPage = () => {
  return (
    <DynamicMap />
  );
};
```

**Comment by danieltkach** [comment] 2021-09-21 20:51
1

In order to run it, the react-leaflet library must be downgraded. These are the steps:

remove react-leaflet: npm uninstall react-leaflet

update your react-scripts version to 3.3.0 or higher: npm install --save react-scripts@latest

remove node_module directory (optional)

clean cache: npm cache clean --force

Install the working versions: npm i react-leaflet@3.1.0 @react-leaflet/core@1.0.2

You can now run the client doing npm start.

**Comment by justrealmilk** [comment] 2021-09-22 08:53
I find it shocking that telling it to target old browsers fixes this.

The issue started occuring for me when I changed

```json
  "browserslist": {
    "production": [
      "last 2 Chrome versions",
      "last 2 Firefox versions",
      "last 2 Safari versions",
      "iOS >= 13",
      "unreleased versions"
    ],
    "development": [
      "last 2 Chrome versions",
      "last 2 Firefox versions",
      "last 10 Safari versions",
      "iOS >= 13",
      "unreleased versions"
    ]
  }
```

to



```json
  "browserslist": {
    "production": [
      "last 2 Chrome versions",
      "last 2 Firefox versions",
      "last 2 Safari versions",
      "iOS >= 14",
      "unreleased versions"
    ],
    "development": [
      "last 2 Chrome versions",
      "last 2 Firefox versions",
      "last 2 Safari versions",
      "iOS >= 14",
      "unreleased versions"
    ]
  }
```

**Closed** 2021-10-09 16:00 UTC

**Comment by ztolley** [comment] 2021-11-05 20:46
Why close an issue that hasn’t been fixed?

**Comment by frontcraft** [comment] 2022-01-20 12:40
This issue is still blocking may people from using the package. It should not be closed indeed.

**Comment by cryptic-ai** [comment] 2022-05-24 18:32
Still having this issue.

**Comment by dennisat** [comment] 2022-05-25 08:05
### Come on... please, respect the open-source reputation.

**Comment by DVGY** [comment] 2022-05-25 08:16
Guys i fixed this issue by forking repo and changing babel.js config. I really think, this fix should exist in react leaftlet as it blocks the usage

**Comment by dennisat** [comment] 2022-05-25 08:34
It is not always easy to change the babel, and it is super ugly in 2022 to add something in babel for just a dependency.

**Comment by DVGY** [comment] 2022-05-25 08:41
> dependenc

https://github.com/PaulLeCam/react-leaflet/issues/966
https://github.com/DVGY/react-leaflet/commit/205437bb8bbfcb73f4778359ce47f6e9080ad491 
This is what I changed to make it work. Again, the user of library should not add this, the maintainer should add this, so that it does not have any problem

**Comment by fervillalbag** [comment] 2023-11-24 19:22
I faced the same issue and was able to resolve it by importing the files separately

```jsx
import { MapContainer } from 'react-leaflet/MapContainer'
import { TileLayer } from 'react-leaflet/TileLayer'
import { useMap } from 'react-leaflet/hooks'
```

**Comment by MiladJoodi** [comment] 2024-03-28 13:13
same issue now 🥺

**Comment by McTom234** [comment] 2024-04-28 15:45
Same issue

**Comment by tayouthae** [comment] 2024-08-15 04:25
Add “use client” to the top of your file.

"use client"
// my code here

NextJS assumes a component is a Server Component unless you explicitly tell NextJS the component you want is a Client Component.

**Comment by xuzhengrong** [comment] 2024-08-21 02:18
I also encountered this problem and solved it in a clumsy way! Since umijs is used as the development framework, configuring babel plugins is extremely inconvenient, so I gave up. Finally, I found the source code of react-leaflet from the node_modules directory. I copied the js files under the two directories of /lib and /node_modules/@react-leaflet/core/lib into my own code project. Files with the suffix.d.ts don't need to be copied. Then, I modified the copied code, corrected the import path. Finally, I deleted the react-leaflet configuration in package.json and ran npm uninstall. Then it was all right.

**Comment by blythechan** [comment] 2024-12-11 16:18
```
react-leaflet: "3.2.5", 
@react-leaflet: "1.1.1", 
webpack: "4.47.0"
```

Out of all the alleged solutions, [this answer](https://github.com/PaulLeCam/react-leaflet/issues/891#issuecomment-911819326) worked for me. To expand on the answer, I tweaked mine a bit to something akin to this:
```
{
     test: /\(js|jsx)$/,
     include: [ path.resolve(__dirname, "src"), path.resolve(__dirname, "node_modules/react-leaflet") ],
     use: {
          loader: 'babel-loader',
          presets: [
               "@babel/preset-env",
               "@babel/preset-react"
          ],
          plugins: [
               "@babel/plugin-proposal-nullish-operator", // version 7.24.6; ??
               "@babel/plugin-proposal-optional-chaining" // .?
         ]
     }
}
```
