### ISSUE TITLE
Set icon making marker draggable again

### ISSUE THREAD

**Issue by antoniopuero** [PaulLeCam/react-leaflet#178] opened 2016-06-24 14:38 UTC
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Check that you are using a supported version of React (v0.14 or v15).
- [x] Check that you are using a supported version of Leaflet (v.0.7)
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md#technical-considerations).

### Expected behavior

We are using leaflet icon as an icon so inside the componentDidUpdate method check like `this.props.icon !== prevProps.icon` is always true. It triggers setIcon method. This method is making marker draggable again [here is the original issue](https://github.com/Leaflet/Leaflet/issues/3807)
### Actual behavior
The marker is draggable even I've changed my draggable prop to false
### Steps to reproduce
```javascript 
<Marker
          draggable={props.draggable} //true on init
          ... 
          icon={L.icon({
                      iconUrl: "some/icon.png",
                      iconSize: [35, 50],
                      iconAnchor: [25, 45]
                    })
           }
/>
```
then update props.drggable to false and you'll still get drggable marker.

This behavior could be fixed by setting more complex check on the icon property or by allowing to use leaflet version 1.0.0-rc.1

here is the proof [this jsfiddle](https://jsfiddle.net/q2v7t59h/35/).

**Comment by PaulLeCam** [comment] 2016-06-24 16:18
It seems to be an issue in Leaflet itself and not caused by this library, so you'll have to wait for a fix upstream or implement a workaround yourself.

**Comment by antoniopuero** [comment] 2016-06-25 07:31
The fix has been released already, but your peerDependency doesn't allow me to install version later than 0.7.x. and another reason is checking for the identity of two objects (leaflet icon), otherwise, setIcon is called every propagation cycle.

**Comment by PaulLeCam** [comment] 2016-06-25 07:58
`peerDependencies` does not constraint you in any way using npm 3, if you want to use another version you can set it in your own `package.json`, but this library is not made to be compatible with Leaflet v1 yet, so it won't be supported until then.
So you can either implement a fix in your application code or wait for a release compatible with Leaflet v1, but I don't plan on implementing a fix in this lib itself as it's an issue from Leaflet.

**Closed** 2016-06-27 11:49 UTC
Labels: wontfix
