### ISSUE TITLE
React leaflet does not render properly, not functioning

### ISSUE THREAD

**Issue by inovramadani** [PaulLeCam/react-leaflet#1052] opened 2022-12-12 08:36 UTC
### Expected behavior

Should function as leaflet JS.

### Actual behavior

Broken maps, not functioning at all

### Steps to reproduce

Go quickly to the sandbox and you will know quickly:
https://codesandbox.io/s/react-leaflet-bug-sw6i8o?file=/src/App.js

![image](https://user-images.githubusercontent.com/27492820/206998841-241645fb-4df3-4119-8dad-16cf5970b3df.png)

**Comment by blitz2200** [comment] 2022-12-12 09:23
exactly same here

**Comment by inovramadani** [comment] 2022-12-12 09:34
It's ok if I use: 
```
react-leaflet@3.2.0
leaflet@1.6.0
```

**Comment by macrouch** [comment] 2022-12-16 16:09
`import "leaflet/dist/leaflet.css";`

**Comment by almahdi404** [comment] 2022-12-27 18:49
it should be closed now.

**Comment by Arif-un** [comment] 2022-12-30 14:29
Solved this issue by installing `leaflet`
and
`import "leaflet/dist/leaflet.css";`

Style files should be kept with `react-leaflet` package or mentioned in docs.

**Comment by HanlinTheDEVELOPER** [comment] 2023-01-12 06:11
I already tried every methods mention above but the map is still broken

**Comment by jcable** [comment] 2023-01-13 16:39
with 
    react-leaflet@3.2.0
    leaflet@1.6.0
I get leaflet@1.7.1 is required but both require react 17 and I'm on react 18.
with react-leaflet 4.2.0 and leaftlet 1.9.3 without the CSS import I get fragmented maps not alligned. With the CSS import I get nothing at all

**Comment by revidovich** [comment] 2023-01-14 11:18
![image](https://user-images.githubusercontent.com/63742797/212469346-3cc3eec5-5a1e-45ab-aa7a-81544edd5f38.png)
  
        "leaflet": "^1.9.3",
        "react": "18.2.0",
        "react-dom": "18.2.0",
        "react-leaflet": "^4.2.0",

**Comment by jcable** [comment] 2023-01-22 10:40
I've got it working. The problem is that the mandatory height attribute has to be applied to the div that's rendered by the react MapContainer JSX element. It's not obvious and it would be really helpful if height were an explicit prop.

I've made it work by adding an id property to the MapContainer and giving that an explicit height style outside the react framework.

**Comment by artem-ara** [comment] 2023-02-08 13:59
So, if you are having the problems described above, you need to:
1. Add: `import 'leaflet/dist/leaflet.css';` to your react component 
2. Add `style={{ height: **536** }}`.  Noticed, that height: 'style={{ height: '536**px**' }}' **doesn't work**

**Comment by fabian-0520** [comment] 2023-02-09 11:13
> So, if you are having the problems described above, you need to:
> 
> 1. Add: `import 'leaflet/dist/leaflet.css';` to your react component
> 2. Add `style={{ height: 536 }}`.  Noticed, that height: 'style={{ height: '536**px**' }}' **doesn't work**

Confirming that this workaround also works with the latest React and Leaflet versions. Thanks!

**Comment by fathah** [comment] 2023-06-11 15:38
I tried these. But i am gettings a blank

![image](https://github.com/PaulLeCam/react-leaflet/assets/48355244/15a54559-d33e-4685-9dea-d8f4f24ed760)

```javascript

 <div  className='border-2'
        style={{
            maxWidth: '50vw',
            height: 536
        }}>
              <MapContainer center={position} zoom={13} scrollWheelZoom={false}>
    <TileLayer
      attribution=''
      url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
    />
    <Marker position={position}>
      <Popup>
        A pretty CSS3 popup. <br /> Easily customizable.
      </Popup>
    </Marker>
  </MapContainer>
        </div>
```

**Comment by Gyvastis** [comment] 2023-06-30 09:57
Import the css file and add this additionally 
```css
    .leaflet-container {
        height: 300px;
    }
```

**Comment by barbalex** [comment] 2023-07-16 11:20
Seems to me this can be closed as adding height to `.leaflet-container` and importing `leaflet/dist/leaflet.css` solves the issue.

**Comment by issam-seghir** [comment] 2023-11-29 20:24
try this
```jsx
import { MapContainer, TileLayer, Marker, Popup, useMap } from "react-leaflet";

const ComponentResize = () => {
	const map = useMap();

	setTimeout(() => {
		map.invalidateSize();
	}, 0);

	return null;
};


const Map = () => {
	const position = [36.0339, 1.6596];

	return (
		<MapContainer
			style={{
				height: "100%",
				width: "100%",
			}}
			center={position}
			attributionControl={true}
			zoom={8}
			minZoom={3}
			scrollWheelZoom={true}
		>
			<ComponentResize />
			<TileLayer
				// className={'ion-hide'}
				attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
				url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
			/>
			<Marker position={position}>
				<Popup>
					A pretty CSS3 popup. <br /> Easily customizable.
				</Popup>
			</Marker>
		</MapContainer>
	);
};

export default Map;

```

**Comment by oldtune** [comment] 2023-12-26 00:27
> So, if you are having the problems described above, you need to:
> 
>     1. Add: `import 'leaflet/dist/leaflet.css';` to your react component
> 
>     2. Add `style={{ height: 536 }}`.  Noticed, that height: 'style={{ height: '536**px**' }}' **doesn't work**

This worked for me, the tile was broken but adding the fixed height fixed the problem. The height is up to you and doesn't have to be a fixed 536

**Comment by abid365** [comment] 2024-03-06 18:09
I just made the height of the mapcontainer 100%, any height given will display the map, and don't forget to use to CSS provided by leaflet mentioned above
`<MapContainer
      className="h-[100%]"
      center={[51.505, -0.09]}
      zoom={13}
      scrollWheelZoom={true}
    >
      <TileLayer
        attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
      />
      <Marker position={[51.505, -0.09]}>
        <Popup>
          A pretty CSS3 popup. <br /> Easily customizable.
        </Popup>
      </Marker>
    </MapContainer>`

**Comment by ImLunaHey** [comment] 2024-03-24 04:26
Fully working example for nextjs.

```tsx
'use client';
import { LatLngExpression } from 'leaflet';
import { MapContainer, Marker, Popup, TileLayer } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';

type MapProps = {
  position: LatLngExpression;
};

export default function Map({ position }: MapProps) {
  return (
    // Height or width must be set for the map to display
    <div className="w-full">
      <MapContainer center={position} zoom={13} scrollWheelZoom={false} className="h-full">
        <TileLayer
          attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        />
        <Marker position={position}>
          <Popup>
            A pretty CSS3 popup. <br /> Easily customizable.
          </Popup>
        </Marker>
      </MapContainer>
    </div>
  );
}
```

To avoid the error of window missing use dynamic import.

```ts
const Map = dynamic(() => import('@/components/map'), {
  ssr: false,
  loading: () => <p>Loading...</p>,
});
```

**Comment by ZeynalliZeynal** [comment] 2024-05-09 20:21
I dont know why but it is very annoying problem. i have the same issue and i ensure you that there is nothing left that i can try to solve this problem. 
`
`

**Comment by ZeynalliZeynal** [comment] 2024-05-09 20:25
> I dont know why but it is very annoying problem. i have the same issue and i ensure you that there is nothing left that i can try to solve this problem.
> 
> ```js
> import { MapContainer, Marker, Popup, TileLayer } from 'react-leaflet';
> import 'leaflet/dist/leaflet.css';
> 
> export default function ContactLocation() {
> 
>   return (
>     <section>
>       <div className="container max-w-full">
>         <MapContainer
>           center={[-3.745, -38.523]}
>           zoom={13}
>           scrollWheelZoom={false}
>           className="h-full"
>         >
>           <TileLayer
>             attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
>             url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
>           />
>           <Marker position={[-3.745, -38.523]}>
>             <Popup>
>               A pretty CSS3 popup. <br /> Easily customizable.
>             </Popup>
>           </Marker>
>         </MapContainer>
>       </div>
>     </section>
>   );
> }
> ```
> 
> ![looks like this](https://private-user-images.githubusercontent.com/145213835/329377536-bfaf6cdb-2b89-4293-828b-f1ee88149041.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyODY0OTYsIm5iZiI6MTcxNTI4NjE5NiwicGF0aCI6Ii8xNDUyMTM4MzUvMzI5Mzc3NTM2LWJmYWY2Y2RiLTJiODktNDI5My04MjhiLWYxZWU4ODE0OTA0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQyMDIzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDlkODQ5ZWUyYTgyOTJjYjVjNzE5MGQ3ZDJhNDY0MWMxNTBhNGVjMmNlMjZmMWZlNzgyYzE1ODQzYjRhZGRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WyZgYFyrsM-hJXTZTK-aPGuYLz68_Y1K4hUwDpHQUxM)

when i dont import css it looks like this
![image](https://github.com/PaulLeCam/react-leaflet/assets/145213835/fd30d137-4349-4daa-aa4c-4341149ac141)

![image](https://github.com/PaulLeCam/react-leaflet/assets/145213835/f1ea53e3-0d57-40d7-b831-889cc99e288d)

**Closed** 2024-05-25 13:57 UTC

**Comment by atefBB** [comment] 2024-10-03 11:06
> So, if you are having the problems described above, you need to:
> 
> 1. Add: `import 'leaflet/dist/leaflet.css';` to your react component
> 2. Add `style={{ height: 536 }}`.  Noticed, that height: 'style={{ height: '536**px**' }}' **doesn't work**

Under the hood, react add `px` suffix to any props that should be considered as something that can be calculated in `pixels` such as `height`, `margin`, `width` ..., hope to be clear.

**Comment by guilhermefrag** [comment] 2025-01-03 19:09
Try to add those lines of code:
```
.leaflet-container {
    height: 500px;
    width: 100%;
}
```
To the file that contains:
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Comment by teddybee** [comment] 2025-01-26 14:56
Is there any chance to make the map full height of the page?
The css height 100% is not working, also the taailwind h-full or min-h-full class eighter

**Comment by muhidhossain** [comment] 2025-01-28 11:34
Adding this in the `MapContainer` worked for me:
`style={{ height: '100svh', width: '100vw' }}`

The `height` and `width` properties don't function exactly the same as their CSS counterparts. They work with certain values, but for others, like `100%`, they do not work.

**Comment by jonamat** [comment] 2025-03-11 10:23
> I dont know why but it is very annoying problem. i have the same issue and i ensure you that there is nothing left that i can try to solve this problem. what i discovered and end up with is that it does work only if you set up with create-react-app, it doesnt when you set up with vite. so i dont know how to solve this for vite, maybe in the vite.config.js file.
> 
> import { MapContainer, Marker, Popup, TileLayer } from 'react-leaflet';
> import 'leaflet/dist/leaflet.css';
> 
> export default function ContactLocation() {
> 
>   return (
>     <section>
>       <div className="container max-w-full">
>         <MapContainer
>           center={[-3.745, -38.523]}
>           zoom={13}
>           scrollWheelZoom={false}
>           className="h-full"
>         >
>           <TileLayer
>             attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
>             url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
>           />
>           <Marker position={[-3.745, -38.523]}>
>             <Popup>
>               A pretty CSS3 popup. <br /> Easily customizable.
>             </Popup>
>           </Marker>
>         </MapContainer>
>       </div>
>     </section>
>   );
> }
> ![looks like this](https://github.com/PaulLeCam/react-leaflet/assets/145213835/bfaf6cdb-2b89-4293-828b-f1ee88149041)

Did you find a solution to fix this in vitejs?

**Comment by maryamaljanabi** [comment] 2025-03-21 18:31
> So, if you are having the problems described above, you need to:
> 
> 1. Add: `import 'leaflet/dist/leaflet.css';` to your react component
> 2. Add `style={{ height: 536 }}`.  Noticed, that height: 'style={{ height: '536**px**' }}' **doesn't work**

I tried everything, what worked for me was adding the height, whether it's with or without "px", also using a percentage works `style={{ height: "100%" }}`. I'm not sure why this wasn't provided in the documentation since without specifying the height and the stylesheet, the map doesn't load correctly at all.

Note: I can confirm this works in `react-leaflet version 5.0.0-rc.2`

**Comment by maryamaljanabi** [comment] 2025-03-21 18:39
> > I dont know why but it is very annoying problem. i have the same issue and i ensure you that there is nothing left that i can try to solve this problem. what i discovered and end up with is that it does work only if you set up with create-react-app, it doesnt when you set up with vite. so i dont know how to solve this for vite, maybe in the vite.config.js file.
> 
> Did you find a solution to fix this in vitejs?

I'm currently working on a react project with vite, it worked for me by adding the stylesheet in addition to the height on the map `<MapContainer ... style={{ height: "100%" }}>`. I'm using react-leaflet v5.

**Comment by markcorrea** [comment] 2025-09-05 19:43
Just got it working (code below)

Notes:
- "leaflet": "1.9.4",
- "react-leaflet": "4.2.0",
- "react": "18.0.0",
- "react-leaflet-markercluster": "4.1.0" (it is not mentioned here, but since I'm using it and I needed to upgrade it as well, thought would be nice to mention);
- TyleLayer HAS to exist inside MapContainer, because it is the component that will render the map. Otherwise you'll get a gray/white background;
- Either adding `style={{ height: 400, width: 400 }}` or the class `.leaflet-container{  height: 500px; }` does the same thing (at least on my config). Try both;
- As previously mentioned, don't forget to import `import 'leaflet/dist/leaflet.css'`;
- There's NO version compatible with both React 17 AND 18. You'll have to upgrade these leaflet libraries at the same moment you upgrade React.
- MOST IMPORTANT: You HAVE to change "render" by "createRoot" as React 18 docs say. THIS is the thing I was forgetting to do even though I had done all the other items. If you don't do it, React will behave like React 17 and your map will keep crashing.

```
import { MapContainer, TileLayer, useMap } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';

const MyComponent = () => {
  const map = useMap();
  console.log('map center:', map.getCenter());
  return null;
};

const Basic = () => {
  return (
    <div style={{ backgroundColor: 'white', display: 'flex' }}>
      <div style={{ padding: 20 }}>
        <MapContainer style={{ height: 400, width: 400 }} center={[50.5, 30.5]} zoom={13}>
          <TileLayer
            attribution='&amp;copy <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
            url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          />
          <MyComponent />
        </MapContainer>
      </div>
    </div>
  );
};


export default Basic;

```
