### ISSUE TITLE
Popup not shown

### ISSUE THREAD

**Issue by armandojacobus** [PaulLeCam/react-leaflet#906] opened 2021-07-27 11:59 UTC
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x ] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x ] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x ] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x ] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x ] The issue has not already been reported.
- [ x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x ] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

That when clicking on the marker in the example, the popup shows when I am in Safari (Osx).
https://react-leaflet.js.org/docs/example-popup-marker

### Actual behavior

The popup in the example code (on the official page itself) doesn't show when clicking on the marker in Safari (Osx). When opening the console, the popup works 1 time.
In Chrome it does work as expected

### Steps to reproduce

Open Safari.
Go to https://react-leaflet.js.org/docs/example-popup-marker
Click on the marker.

**Comment by PaulLeCam** [comment] 2021-08-01 15:59
Duplicate of https://github.com/PaulLeCam/react-leaflet/issues/874

**Closed by PaulLeCam** 2021-08-01 15:59 UTC
