### ISSUE TITLE
Pinch zoom does not work on samsung phones

### ISSUE THREAD

**Issue by EvertLagerberg** [PaulLeCam/react-leaflet#337] opened 2017-06-09 15:09 UTC
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v15.x).
- [x] Using the supported version of Leaflet (v1.x) and its corresponding CSS file is loaded.
- [x] Using the latest version of React-Leaflet.
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/docs/How%20it%20works.md#limitations).

### Expected behavior
Pinch zoom should work on phones even when dragging is set to false. I have tested that this works on Iphone 6. This works on samsung phones on standard leaflet lib.

### Actual behavior

Pinch zoom does not work on Samsung phones (tested on S6 Edge & S5) when `dragging=false`.

### Steps to reproduce
1. (Standard leaflet lib, works fine) Test to pinch zoom in this example with samsung phone:
http://jsfiddle.net/LnzN2/951/
2. (React-Leaflet, does not work) Test to pinch zoom in this example with samsung phone:
https://jsfiddle.net/3dfsgj4r/18/

**Comment by PaulLeCam** [comment] 2017-06-11 10:07
Sorry but I have no way to reproduce this so please open a PR with a fix if you have one.

**Comment by PaulLeCam** [comment] 2017-06-15 19:33
Your jsfiddle is using an outdated version of the library.

**Comment by EvertLagerberg** [comment] 2017-06-15 19:40
Sorry about that. I updated the jsfiddle.

**Comment by EvertLagerberg** [comment] 2017-06-27 08:18
@PaulLeCam Would you consider opening this ticket again?

**Comment by PaulLeCam** [comment] 2017-06-27 08:45
I don't mind reopening it but I have no way to reproduce it, so please open a PR if you have a fix.

**Comment by EvertLagerberg** [comment] 2017-06-27 18:09
@PaulLeCam Unfortunately I don't have a fix. Could this be a related issue: https://github.com/Leaflet/Leaflet/issues/5310 ?

**Comment by barbalex** [comment] 2018-07-05 20:47
@EvertLagerberg  On my Samsung S8+ your example only pinch-zooms when I set dragging to true

**Comment by PaulLeCam** [comment] 2020-12-13 15:31
Closing as it seems to be fixed in Leaflet

**Closed by PaulLeCam** 2020-12-13 15:31 UTC
Labels: help wanted, needs investigation
