### ISSUE TITLE
Close button on popup

### ISSUE THREAD

**Issue by benzen** [PaulLeCam/react-leaflet#169] opened 2016-06-01 14:52 UTC
Please make sure to check the following boxes before submitting an issue. Thanks!

- [x ] Check that all peer dependencies are installed: React, ReactDOM and Leaflet.
- [ x] Check that you are using a supported version of React (v0.14 or v15).
- [ x] Check that you are using a supported version of Leaflet (v.0.7)
- [ x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [ x] Make sure you have fully read the [documentation](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md) and that you understand the [technical considerations](https://github.com/PaulLeCam/react-leaflet/blob/master/README.md#technical-considerations).

### Expected behavior

Have a nice way or at least an example of how to control the visibility of the popup.

### Actual behavior
We only have an example of how to produce a popup.

I saw the example that produce a popup.
But I want to be able to control the popup appearance the same way we can control the text in an input.

**Comment by benzen** [comment] 2016-06-01 15:58
Here is what i've tryed (here the props map and layerContainer are exclude for clarrity sake):

    (showPopup, onToggle) =>
        <Marker onClick={onToggle}> {showPopup ? 
            <Popup>
              <div>
                <div onClick={onToggle}>close</div>
                  My popup
              </div>
            </Popup> 
        : null} </Marker>

When adding the popup all is good. When I try to remove the popup (by clicking on the close text), i've got he following error:

    Uncaught TypeError: listeners[i].action.call is not a function   leaflet-src.js:461

Expected results
===============

No error message and the popup disapears

Actual results
=============

    Uncaught TypeError: listeners[i].action.call is not a function   leaflet-src.js:461

**Comment by PaulLeCam** [comment] 2016-06-08 19:25
Hi,
Could you please provide a jsfiddle to reproduce the problem?
Thanks.

**Comment by jgimbel** [comment] 2016-06-09 17:36
@benzen your option does not open the popup on mount (If that is what you are wanting), it merely calls `bindPopup(<popup>)`. To do this I made a js fiddle to show how you can handle popups with state/flux/redux [here](https://jsfiddle.net/e3zh51fp/1/). 

The problem with this is with the `onPopupclose` event. When you remove a popup from the map, it calls `map.removeLayer(<popup>)`, which removes the popup from the DOM then `popupclose` event fires ([source](https://github.com/Leaflet/Leaflet/blob/878a022897d1800e89f1a20c04167182d28e6aef/src/layer/Popup.js#L158)). When it fires, react changes state, and then re-renders. This unmounts the Popup Component. In Popup's `componentWillUnmount` the function `this.props.map.removeLayer(this.leafletElement)` is then called again([source](https://github.com/PaulLeCam/react-leaflet/blob/master/src/Popup.js#L57)). This causes the popup to try to remove itself from the DOM again, and throws an error. 

This could be simply fixed by checking if this.leafletElement._map is still set. This is unset on removeLayer([source]())

```js
  componentWillUnmount() {
    super.componentWillUnmount();
    this.removePopupContent();
+   if(this.leafletElement._map){
      this.props.map.removeLayer(this.leafletElement);
+   }
  }
```

We cannot use `this.leafletElement._isOpen` because 
1) it is set after `map.removeLayer(this)` is called ([souce](https://github.com/Leaflet/Leaflet/blob/v0.7.7/src/layer/Popup.js#L333)) and 
2) it is not compatible with Leaflet 1.0
`this._map` is how Leaflet 1.0 checks if the popup is open([source](https://github.com/Leaflet/Leaflet/blob/878a022897d1800e89f1a20c04167182d28e6aef/src/layer/Popup.js#L257)), and is also compatible with Leaflet 0.7.

**Comment by PaulLeCam** [comment] 2016-06-09 18:46
OK if I understand the problem correctly I think the issue is that you are trying to control the opening state of the popup in your component while also letting Leaflet control it itself, it can't work as you expect.
Either you can let Leaflet handle this opening state by itself, and use its events to reflect this state in your app, or you need to prevent Leaflet from handling this state itself, and drive it in your component.

**Comment by jgimbel** [comment] 2016-06-09 18:53
I am unfamiliar with how I can unbind leaflet from controlling the state. Can you point me towards some docs?

**Comment by benzen** [comment] 2016-06-09 19:00
@paullecam thanks for you detailed answer, very apperciated.
At the end of the day, this issue has the same roots than wanting to
control the view port from react.

Leaftlet isn't ment for that, so as you propose, i'll let leaflet handle
it's stuff, an just keep track of it current state (via events) for the
rest of my app.

Keep on with the good work.
Regards

2016-06-09 14:53 GMT-04:00 Joel <notifications@github.com>:

> I am unfamiliar with how I can unbind leaflet from controlling the state.
> Can you point me towards some docs?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/PaulLeCam/react-leaflet/issues/169#issuecomment-224991551>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIihar-1hPfcN-O_4aty2TUPsul-hzdks5qKGErgaJpZM4Iroi3>
> .
>



-- 
Benjamin DREUX

**Comment by PaulLeCam** [comment] 2016-06-09 19:44
@jgimbel I haven't use these so I don't know how Leaflet handles them, but Popup has the [`closeButton`](http://leafletjs.com/reference.html#popup-closebutton) and [`closeOnClick`](http://leafletjs.com/reference.html#popup-closeonclick) options that seem to have the wanted behavior.

@benzen yes it's quite tricky sometimes to make sure the state of the app is consistent having Leaflet maintain its own, but I find it easier to always consider it as the source of truth regarding the actual display of the map.

**Comment by jgimbel** [comment] 2016-06-09 20:24
I updated the [jsfiddle](https://jsfiddle.net/e3zh51fp/2/) to use those options, and all works. Thanks for the direction. As a note, using multiple popups this way can be risky, as you have to make sure only one popup is open in your state to keep consistency with the leaflet state.

**Closed** 2016-06-16 09:49 UTC

**Comment by Luca1995it** [comment] 2019-02-25 21:00
I found a way to do this, hope it will helps new users:
https://stackoverflow.com/questions/52085768/close-popup-react-leaflet-after-user-click-on-button-in-popup/54874575#54874575
