### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by jamg26** [PaulLeCam/react-leaflet#879] opened 2021-05-16 21:03 UTC
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [x] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

I have two projects with the same version of React leaflet. But the other one is not working

### Actual behavior

./node_modules/@react-leaflet/core/esm/path.js 10:41
Module parse failed: Unexpected token (10:41)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   useEffect(function updatePathOptions() {
|     if (props.pathOptions !== optionsRef.current) {
|       const options = props.pathOptions ?? {};
|       element.instance.setStyle(options);
|       optionsRef.current = options;

### Steps to reproduce

> {
  "name": "client",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "antd": "^4.15.4",
    "axios": "^0.21.1",
    "http-proxy-middleware": "^0.21.0",
    "leaflet": "^1.7.1",
    "leaflet-ant-path": "^1.3.0",
    "leaflet-routing-machine": "^3.2.12",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-leaflet": "^3.1.0",
    "react-redux": "^7.2.3",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^4.0.3",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.9",
    "redux-thunk": "^2.3.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by kaditya97** [comment] 2021-05-17 00:34
Same problem

**Comment by lluttrell** [comment] 2021-05-17 00:52
I'm having this issue as well but looking into it looks like it's not a react-leaflet problem. The ?? operator looks like it doesn't work with babel-loader for the default browserlist when you use create-react-app?

**Comment by hongsh93** [comment] 2021-05-17 05:15
I use react-app-rewired ver 2.1.6 to start and I have the same issue

**Comment by sthenault** [comment] 2021-05-17 10:20
as I get it this is a compilation problem, which probably targets too recent js version (es2020) 

About the nullish operator : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

**Comment by nnatter** [comment] 2021-05-17 11:01
We are running into the same issue. We are using `"react-leaflet": ">=3.1.0 <3.2.0 || ^3.2.1"` in our `package.json` for now to skip the newly released `3.2.0` version.

**Comment by nnatter** [comment] 2021-05-17 11:16
We are running into the same problem. We have added the following lines in our `package.json` for now to skip the newly released `1.1.0` version of the `@react-leaflet/core` package as a quickfix:

```
"react-leaflet": ">=3.1.0 <3.2.0 || ^3.2.1",
"@react-leaflet/core": ">=1.0.0 <1.1.0 || ^1.1.1"
```

**Comment by SepidehM** [comment] 2021-05-17 14:04
> We are running into the same problem. We have added the following lines in our `package.json` for now to skip the newly released `1.1.0` version of the `@react-leaflet/core` package as a quickfix:
> 
> ```
> "react-leaflet": ">=3.1.0 <3.2.0 || ^3.2.1",
> "@react-leaflet/core": ">=1.0.0 <1.1.0 || ^1.1.1"
> ```

I did this solution but it dose not work correct :(
![Untitled](https://user-images.githubusercontent.com/9035781/118501866-66791a00-b73e-11eb-81f0-540f5434e94a.png)

**Comment by PaulLeCam** [comment] 2021-05-17 16:08
Duplicate of https://github.com/PaulLeCam/react-leaflet/issues/877

**Closed by PaulLeCam** 2021-05-17 16:08 UTC

**Comment by danieltkach** [comment] 2021-07-31 05:04
So what's the fix for this? I'm getting:
Module parse failed: Unexpected token (10:41)       
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   useEffect(function updatePathOptions() {
|     if (props.pathOptions !== optionsRef.current) {
>       const options = props.pathOptions ?? {};
|       element.instance.setStyle(options);
|       optionsRef.current = options;
