### ISSUE TITLE
You May need additional loader to handle the result of these loaders

### ISSUE THREAD

**Issue by samuelsodhs** [PaulLeCam/react-leaflet#881] opened 2021-05-18 08:20 UTC
## Bug report

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [ ] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [ ] Using a supported version of React and ReactDOM (v17.0.0 minimum).
- [ ] Using the supported version of Leaflet (v1.7.1 minimum) and its corresponding CSS file is loaded.
- [ ] Using the [latest v3 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [ ] The issue has not already been reported.
- [ ] Make sure you have followed the [quick start guide](http://leafletjs.com/examples/quick-start.html) for Leaflet.
- [ ] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

Please describe.

### Actual behavior

Please describe.

### Steps to reproduce

Please provide the simplest example possible to reproduce the issue, based on [this CodePen](https://codepen.io/PaulLeCam/pen/xxOgovP).

**Comment by samuelsodhs** [comment] 2021-05-18 08:21
./node_modules/@react-leaflet/core/esm/path.js 10:41
Module parse failed: Unexpected token (10:41)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   useEffect(function updatePathOptions() {
|     if (props.pathOptions !== optionsRef.current) {
>       const options = props.pathOptions ?? {};
|       element.instance.setStyle(options);
|       optionsRef.current = options;

**Comment by Sata51** [comment] 2021-05-18 09:06
In my case, this has removed the issue https://github.com/facebook/create-react-app/issues/9468#issuecomment-694191642

**Comment by anthify** [comment] 2021-05-18 10:29
If you're using Next.js the only way I've been able to get it to work is by using [`next-transpile-modules`](https://github.com/martpie/next-transpile-modules)

```javascript
// next.config.js

const withTM = require("next-transpile-modules")([
  "react-leaflet",
  "@react-leaflet/core",
]);

module.exports = withTM(); 
```

**Comment by nnatter** [comment] 2021-05-18 14:39
You might be able to fix this by using the `@babel/plugin-proposal-nullish-coalescing-operator` in your project. See https://github.com/PaulLeCam/react-leaflet/issues/883 for why this is happening.

**Comment by gurpreerrajpal** [comment] 2021-05-18 15:38
Hello Guys,

Getting same error while building my next js project and none of the solution is working for me mentioned here.

https://exerror.com/failed-to-compile-node_modules-react-leaflet-core-esm-path-js-1041-module-parse-failed-unexpected-token-1041/

Please help me or shall we remove this module and use any other since we got a BUG here now.

PLEASE HELP!!!!!!!

**Comment by gurpreerrajpal** [comment] 2021-05-18 15:39
![Screenshot from 2021-05-18 21-09-00](https://user-images.githubusercontent.com/25425829/118681559-4cfacf80-b81d-11eb-98ef-628931f7f2be.png)

**Comment by anthify** [comment] 2021-05-19 07:32
@gurpreerrajpal have you tried my recommendation? It worked perfectly fine for me after doing this.

> If you're using Next.js the only way I've been able to get it to work is by using [`next-transpile-modules`](https://github.com/martpie/next-transpile-modules)
> 
> ```js
> // next.config.js
> 
> const withTM = require("next-transpile-modules")([
>   "react-leaflet",
>   "@react-leaflet/core",
> ]);
> 
> module.exports = withTM({
>   future: {
>     webpack5: true
>   }
> }); 
> ```

**Comment by gurpreerrajpal** [comment] 2021-05-19 08:55
@anthify How can i write this ? I have to use withCSS as well. Appriciate your help!

    "@react-leaflet/core",
]);

module.exports = withTM({
    future: {
        webpack5: true
    }
});

module.exports = withCSS({
    cssLoaderOptions: {
        url: false
    },
    onDemandEntries: {
        // period (in ms) where the server will keep pages in the buffer
        maxInactiveAge: 1000 * 60 * 60 * 24 * 30, // 1 month
        // number of pages that should be kept simultaneously without being disposed
        pagesBufferLength: 100,
    },
    env: dotenv.config().parsed,
});

**Comment by gurpreerrajpal** [comment] 2021-05-22 15:08
hello guys?????? anyone able to fix it???

**Comment by yodivanbaped** [comment] 2021-05-28 12:22
any other options to solve this problem? I've tried all the solutions posted here and still no same issue

**Comment by anthify** [comment] 2021-06-01 14:27
@chaincodedev this should work with your setup. I presume you're using an older version of next.js as you don't need withCSS anymore, but here is how you'd compose those plugins.

```javascript
const withPlugins = require("next-compose-plugins");
const withCSS = require("..."); // <-- Add in your withCSS package
const withTM = require("next-transpile-modules")([
  "react-leaflet",
  "@react-leaflet/core",
]);

module.exports = withPlugins([
  [
    withTM,
    {
      future: {
        webpack5: true,
      },
    },
  ],
  [
    withCSS,
    {
      cssLoaderOptions: {
        url: false,
      },
      onDemandEntries: {
        // period (in ms) where the server will keep pages in the buffer
        maxInactiveAge: 1000 * 60 * 60 * 24 * 30, // 1 month
        // number of pages that should be kept simultaneously without being disposed
        pagesBufferLength: 100,
      },
      env: dotenv.config().parsed,
    },
  ],
]);
```

**Comment by jlahd** [comment] 2021-06-09 08:37
Here's my workaround for this one (create-react-app, latest react-leaflet). Hopefully useful for someone stumbling on the issue as well. The browser list changes suggested above did not work for me (`yarn start` just forced a refresh of the configuration).

I ended up using the two libraries [react-app-rewired](https://github.com/timarney/react-app-rewired) and [react-app-rewire-babel-loader](https://github.com/dashed/react-app-rewire-babel-loader). Steps necessary:

1. `yarn add -D react-app-rewired react-app-rewire-babel-loader`
2. Change script names in `package.json` according to the instructions for react-app-rewired:
```json
  /* package.json */

  "scripts": {
-   "start": "react-scripts start",
+   "start": "react-app-rewired start",
-   "build": "react-scripts build",
+   "build": "react-app-rewired build",
-   "test": "react-scripts test",
+   "test": "react-app-rewired test",
    "eject": "react-scripts eject"
}
```
3. Create `config-overrides.js` in the project's root according to instructions for react-app-rewire-babel-loader:
```
/* config-overrides.js */

const path = require("path");
const fs = require("fs");
const rewireBabelLoader = require("react-app-rewire-babel-loader");
 
const appDirectory = fs.realpathSync(process.cwd());
const resolveApp = relativePath => path.resolve(appDirectory, relativePath);

module.exports = function override(config, env) {
    config = rewireBabelLoader.include(
        config,
        resolveApp("node_modules/@react-leaflet")
    );
    config = rewireBabelLoader.include(
        config,
        resolveApp("node_modules/react-leaflet")
    );

    return config;
};
```

And then it works. Basically, this includes react-leaflet in babel transpilation, correctly processing the `??` operators.

**Comment by mkarkachov** [comment] 2021-06-10 06:00
> If you're using Next.js the only way I've been able to get it to work is by using [`next-transpile-modules`](https://github.com/martpie/next-transpile-modules)
> 
> ```js
> // next.config.js
> 
> const withTM = require("next-transpile-modules")([
>   "react-leaflet",
>   "@react-leaflet/core",
> ]);
> 
> module.exports = withTM({
>   future: {
>     webpack5: true
>   }
> }); 
> ```

This one works great for me. Now I get just warning when running **yarn dev**
`Watchpack Error (initial scan): Error: ENOTDIR: not a directory, scandir '/home/mikhail/work/kupuy-deshevshe/node_modules/next/dist/next-server/lib/router/utils/resolve-rewrites.js'`

**Comment by vanshitamanral** [comment] 2021-06-10 06:25
restricting the react-leaflet to the older versions might help some of you, as it helped me :)
```

     "react-leaflet": ">=3.1.0 <3.2.0 || ^3.2.1",
    "@react-leaflet/core": ">=1.0.0 <1.1.0 || ^1.1.1",
```
also updating the browsers list to 
"browserslist":[
      ">0.2%",
      "not dead",
      "not op_mini all"
    ] 
and then remove the node modules folder.
type in npm install in the terminal 
and then npm start and this might solve your issue :)

**Comment by josegoval** [comment] 2021-07-14 10:27
> If you're using Next.js the only way I've been able to get it to work is by using [`next-transpile-modules`](https://github.com/martpie/next-transpile-modules)
> 
> ```js
> // next.config.js
> 
> const withTM = require("next-transpile-modules")([
>   "react-leaflet",
>   "@react-leaflet/core",
> ]);
> 
> module.exports = withTM({
>   future: {
>     webpack5: true
>   }
> }); 
> ```

Use version 7.2.0. 
```json
"next-transpile-modules": "^7.2.0",
```

Version 8.0.0 give the next error:

```bash
(node:16082) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of undefined
    at handleExternals (projectPath/node_modules/next/dist/build/webpack-config.js:36:23)
    at webpackConfig.externals (projectPath/node_modules/next/dist/build/webpack-config.js:78:149)
    at projectPath/node_modules/next-transpile-modules/src/next-transpile-modules.js:238:46
    at handleExternals (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:61039:17)
    at next (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:61027:9)
    at handleExternals (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:61032:7)
    at projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:61062:5
    at projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:67817:5
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:47182:10), <anonymous>:6:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:47119:20)
    at NormalModuleFactory.create (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:67798:28)
    at projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:54821:14
    at Semaphore.acquire (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:93226:4)
    at asyncLib.forEach.err.stack (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:54819:15)
    at arrayEach (projectPath/node_modules/next/dist/compiled/neo-async/async.js:1:5951)
    at Object.each (projectPath/node_modules/next/dist/compiled/neo-async/async.js:1:9550)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16082) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:16082) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:16082) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of undefined
    at handleExternals (projectPath/node_modules/next/dist/build/webpack-config.js:36:23)
    at webpackConfig.externals (projectPath/node_modules/next/dist/build/webpack-config.js:78:149)
    at projectPath/node_modules/next-transpile-modules/src/next-transpile-modules.js:238:46
    at handleExternals (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:61039:17)
    at next (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:61027:9)
    at handleExternals (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:61032:7)
    at projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:61062:5
    at projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:67817:5
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:47182:10), <anonymous>:6:1)
    at NormalModuleFactory.create (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:67798:28)
    at projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:54821:14
    at Semaphore.acquire (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:93226:4)
    at asyncLib.forEach.err.stack (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:54819:15)
    at arrayEach (projectPath/node_modules/next/dist/compiled/neo-async/async.js:1:5951)
    at Object.each (projectPath/node_modules/next/dist/compiled/neo-async/async.js:1:9550)
    at Compilation.addModuleDependencies (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:54797:12)
(node:16082) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:16082) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of undefined
    at handleExternals (projectPath/node_modules/next/dist/build/webpack-config.js:36:23)
    at webpackConfig.externals (projectPath/node_modules/next/dist/build/webpack-config.js:78:149)
    at projectPath/node_modules/next-transpile-modules/src/next-transpile-modules.js:238:46
    at handleExternals (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:61039:17)
    at next (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:61027:9)
    at handleExternals (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:61032:7)
    at projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:61062:5
    at projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:67817:5
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:47182:10), <anonymous>:6:1)
    at NormalModuleFactory.create (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:67798:28)
    at projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:54821:14
    at Semaphore.acquire (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:93226:4)
    at asyncLib.forEach.err.stack (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:54819:15)
    at arrayEach (projectPath/node_modules/next/dist/compiled/neo-async/async.js:1:5951)
    at Object.each (projectPath/node_modules/next/dist/compiled/neo-async/async.js:1:9550)
    at Compilation.addModuleDependencies (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:54797:12)
(node:16082) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:16082) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of undefined
    at handleExternals (projectPath/node_modules/next/dist/build/webpack-config.js:36:23)
    at webpackConfig.externals (projectPath/node_modules/next/dist/build/webpack-config.js:78:149)
    at projectPath/node_modules/next-transpile-modules/src/next-transpile-modules.js:238:46
    at handleExternals (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:61039:17)
    at next (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:61027:9)
    at handleExternals (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:61032:7)
    at projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:61062:5
    at projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:67817:5
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:47182:10), <anonymous>:6:1)
    at NormalModuleFactory.create (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:67798:28)
    at projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:54987:18
    at Semaphore.acquire (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:93226:4)
    at Compilation._addModuleChain (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:54986:18)
    at Compilation.addEntry (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:55088:8)
    at projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:59990:19
    at new Promise (<anonymous>)
(node:16082) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:16082) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of undefined
    at handleExternals (projectPath/node_modules/next/dist/build/webpack-config.js:36:23)
    at webpackConfig.externals (projectPath/node_modules/next/dist/build/webpack-config.js:78:149)
    at projectPath/node_modules/next-transpile-modules/src/next-transpile-modules.js:238:46
    at handleExternals (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:61039:17)
    at next (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:61027:9)
    at handleExternals (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:61032:7)
    at projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:61062:5
    at projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:67817:5
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:47182:10), <anonymous>:6:1)
    at NormalModuleFactory.create (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:67798:28)
    at projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:54987:18
    at Semaphore.acquire (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:93226:4)
    at Compilation._addModuleChain (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:54986:18)
    at Compilation.addEntry (projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:55088:8)
    at projectPath/node_modules/next/dist/compiled/webpack/bundle4.js:59990:19
    at new Promise (<anonymous>)
(node:16082) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
```

**Comment by tilnea** [comment] 2021-07-14 11:01
For me, it breaks with storybook

```"@storybook/addon-actions": "^6.3.3",
    "@storybook/addon-essentials": "^6.3.3",
    "@storybook/addon-links": "^6.3.3",
    "@storybook/node-logger": "^6.3.3",
    "@storybook/preset-create-react-app": "^3.2.0",
    "@storybook/react": "^6.3.3",```

and I'm using  `"react-leaflet": "^3.2.0"` 
in a create-react-app

**Comment by DigitalNaut** [comment] 2021-07-16 01:50
(Adding this since it was the first Google search results for me and I had to dig around for a couple of hours.)

For [CRACO](https://github.com/gsoft-inc/craco) using [react-leaflet 3.2.0](https://react-leaflet.js.org/), there's [a simple solution](https://github.com/facebook/create-react-app/issues/9908#issuecomment-747014633) that worked for me that uses the [@babel/babel-plugin-proposal-nullish-coalescing-operator](https://babeljs.io/docs/en/babel-plugin-proposal-nullish-coalescing-operator).

Run:
`npm install --save-dev @babel/plugin-proposal-nullish-coalescing-operator`

And add this to `craco.config.js`:

```
module.exports = {
  babel: {
    plugins: ["@babel/plugin-proposal-nullish-coalescing-operator"],
  },
};
```

**Comment by anthify** [comment] 2021-07-20 11:49
Hey @josegoval 

I'm using the following package versions:

`"next-transpile-modules": "7.1.1"`
`"next": "10.1.3"`
`"react-leaflet": "3.2.0"`
`"leaflet": "1.7.1"`

with Node.js version `12.13.1`

Hopefully that helps

**Comment by KhadijaMahanga** [comment] 2021-07-21 21:23
> For me, it breaks with storybook
> 
> ```
>     "@storybook/addon-essentials": "^6.3.3",
>     "@storybook/addon-links": "^6.3.3",
>     "@storybook/node-logger": "^6.3.3",
>     "@storybook/preset-create-react-app": "^3.2.0",
>     "@storybook/react": "^6.3.3",
> ```
> 
> and I'm using `"react-leaflet": "^3.2.0"`
> in a create-react-app

@tilnea did you find a solution? I am having the same issue. Breaks on storybook

**Comment by Niolak** [comment] 2021-07-22 07:39
@KhadijaMahanga To fix storybook (using create-react-app and react-leaflet 3.2.0), adding @babel/plugin-proposal-nullish-coalescing-operator in dev-dependencies and creating this file works for me:

babel.config.js

```
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          ie: '11',
        },
      },
    ],
    '@babel/preset-react',
  ],
  plugins: ["@babel/plugin-proposal-nullish-coalescing-operator"],
};
```

**Comment by KhadijaMahanga** [comment] 2021-07-22 10:00
@tilnea for storybook, this is what I added.

```
 webpackFinal: async (config) => {
    config.module.rules.push({
      test: /\.(js|jsx)$/,
      loader: require.resolve("babel-loader"),
      options: {
        plugins: [
          "@babel/plugin-proposal-nullish-coalescing-operator",
        ],
      },
    });

    return config;
  },
```

**Comment by Collisio** [comment] 2021-08-06 18:50
We were able to get our Storybook to build on Vercel using the following configuration:

package.json:
```json
"@react-leaflet/core": "1.0.2",
"leaflet": "^1.7.1",
"react-leaflet": "3.1.0",
"storybook": "^6.3.6",
"next": "^11.0.0",
```

.storybook/main.js
```javascript
// other stuff
  webpackFinal: async (config, { configType }) => {
    // more configuration options
    config.module.rules.push({
      test: /\.(js|jsx)$/,
      loader: require.resolve("babel-loader"),
      options: {
        presets: [
          '@babel/preset-env',
          '@babel/preset-react',
        ],
        plugins: [
          "@babel/plugin-proposal-nullish-coalescing-operator",
        ],
      },
    });
    return config;
  },
// other stuff
```

**Comment by nitish166** [comment] 2021-09-19 04:23
> restricting the react-leaflet to the older versions might help some of you, as it helped me :)
> 
> ```
> 
>      "react-leaflet": ">=3.1.0 <3.2.0 || ^3.2.1",
>     "@react-leaflet/core": ">=1.0.0 <1.1.0 || ^1.1.1",
> ```
> 
> also updating the browsers list to
> "browserslist":[
> ">0.2%",
> "not dead",
> "not op_mini all"
> ]
> and then remove the node modules folder.
> type in npm install in the terminal
> and then npm start and this might solve your issue :)

Thanks Man!

**Comment by SohanR** [comment] 2021-09-25 17:53
This helps me to fix exact same problem  https://github.com/facebook/create-react-app/issues/9468#issuecomment-694191642

but after change "Browserlist" do the followings 

   -    Delete your `node_modules` folder
   -    Run `npm cache clean --force`
   -    Run `npm install`


Now everything should work as expected. If the map is not loaded, don't forget to add the leaflet css and js to your page and set the height for your MapContainer. See the [official documentation](https://leafletjs.com/examples/quick-start/) for more information.

**Comment by PaulLeCam** [comment] 2021-10-09 15:59
Duplicate of already closed issue.

**Closed by PaulLeCam** 2021-10-09 15:59 UTC

**Comment by morganney** [comment] 2021-10-10 13:33
@PaulLeCam why do you not want to transpile the nullish coalescing operator before publishing this package?

**Comment by Zerg00s** [comment] 2021-10-18 01:21
Same issue. Tried a clean create-react-app with typescript. Then followed the official react-leaflet tutorial.

![image](https://user-images.githubusercontent.com/2797648/137653227-44c74031-cb2f-4bb2-ab67-5624e8f7e2eb.png)

**Comment by crescit** [comment] 2021-10-30 05:03
Just went down this rabbit hole, and this was the thing that resolved it for me after trying all of the above. Used nvm to go down to node 14 as well. https://github.com/facebook/create-react-app/issues/9468#issuecomment-694191642

**Comment by jbalums** [comment] 2022-10-24 17:03
> In my case, this has removed the issue [facebook/create-react-app#9468 (comment)](https://github.com/facebook/create-react-app/issues/9468#issuecomment-694191642)

thank you this solves my problem

**Comment by davidko5** [comment] 2024-04-25 12:42
Still have this issue. node v12.22.12, yarn 1.22.4, tried editing package.json browsersList + deleting node_modules/.cache as well as adding **_"plugin-transform-nullish-coalescing-operator"_** babel plugin.

**Comment by DigitalNaut** [comment] 2024-04-25 14:50
> Still have this issue. node v12.22.12, yarn 1.22.4, tried editing package.json browsersList + deleting node_modules/.cache as well as adding **_"plugin-transform-nullish-coalescing-operator"_** babel plugin.

Whoa, you have a *very* old version of Node. The latest version is v20. Can you update to a recommended version? (Also, I recommend porting your projects to PNPM instead of Yarn. It's way faster and centralizes your dependencies to save a ton of disk space.)
