### ISSUE TITLE
Grey Map

### ISSUE THREAD

**Issue by NgoKnows** [PaulLeCam/react-leaflet#156] opened 2016-05-07 01:31 UTC
### Expected behavior
Map with fully loaded tiles

### Actual behavior
Sometimes a grey map, sometimes half grey map, but when resizing the screen and/or panning it will load tiles.

### Steps to reproduce
Having trouble reproducing, I am copying the base example (https://jsfiddle.net/paul_lecam/q2v7t59h/) exactly, I am on React 15.2, I have the CSS in the head, and Leaflet 0.7.7, so I have no idea what the problem in because it seems like in isolation there are no issues, but when putting it in my application this occurs. Any ideas?

**Comment by bigsassy** [comment] 2016-05-07 14:39
If you inline the height, does it work properly then?

    <Map style={{height: "600px"}}> // plus whatever other props
        // stuff
    </Map>

**Comment by NgoKnows** [comment] 2016-05-07 16:22
I've been trying both an external stylesheet + className, inline styles like you suggested. It ends up looking like [this](http://imgur.com/ox5v2e1)

**Comment by mikeodell77** [comment] 2016-05-13 13:41
I have been seeing the same thing with my project. Any thoughts?

**Comment by NgoKnows** [comment] 2016-05-13 22:30
@mikeodell77 do you happen to be using Radium or any other inline style library?

**Comment by Hakaze** [comment] 2016-05-14 00:53
Having the same issue, it seems the initial render of map renders 1 row of tiles. Any change to state or props which causes a re-render triggers the full map.

**Comment by evenfrost** [comment] 2016-05-14 20:52
Same here.

**Comment by Hakaze** [comment] 2016-05-16 18:13
i'm using css modules. I had a feeling that the containers aren't being styles fast enough before the map is rendering. This ticket may be related as well #40

**Comment by kingy68** [comment] 2016-05-30 11:00
Hey Guys,

I'm also getting a completely grey map. This it the Map component:

```
import React from 'react'
import { Map, TileLayer } from 'react-leaflet'

class MapPage extends React.Component {
  constructor (props, context) {
    super(props, context)

    this.state = {
      lat: 51.505,
      lng: -0.09,
      zoom: 13
    }
  }

  render () {
    return (
      <Map zoom={this.state.zoom}>
        <TileLayer
          attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
          url='http://{s}.tile.osm.org/{z}/{x}/{y}.png'
        />
      </Map>
    )
  }
}

export default MapPage
```

I then import the Map component into another React component and just add it into the return () function as:

`<MapPage />`

The map shows up as completely grey, when I click and drag in the map, I get the following two errors:

leaflet-src.js:6697 Uncaught TypeError: Cannot read property 'subtract' of undefinedL.Draggable.L.Class.extend._onMove @ leaflet-src.js:6697handler @ leaflet-src.js:6380
22leaflet-src.js:6704 Uncaught TypeError: Cannot read property 'add' of undefinedL.Draggable.L.Class.extend._onMove @ leaflet-src.js:6704handler @ leaflet-src.js:6380

Also, the network traffic shows no tile request calls being made.

Currently using:

React - 0.14.8
react-leaflet - 0.11.1
material-ui - 0.15.0-alpha.2
babel - 6.7.2
Webpack - 1.9.11

Could it be just because I'm running it on a webpack-dev-server and not deployed onto a proper web server?

**Comment by kingy68** [comment] 2016-06-01 13:50
Managed to solve the issue. Problem was that I left out the center={*some position*} in the Map tag. I'm guessing center and zoom are required properties when instantiating a Map object in leaflet. Their doco shows this as the example:

```
// initialize the map on the "map" div with a given center and zoom
var map = L.map('map', {
    center: [51.505, -0.09],
    zoom: 13
});
```

**Comment by drwlrsn** [comment] 2016-06-07 22:28
Oh my sweet mercy. For me this issue was caused by
```
img {
  max-height: 100%
}
```
I also had to pass in styles to the component setting its width and height. Further calling `getLeafletElement().invalidateSize()` in `componentDidMount` also did not work.

**Comment by PaulLeCam** [comment] 2016-06-09 19:51
Closing as it seems due to bad configuration/environment setup, not an actual bug in the lib.
Please make sure you go through all the steps of Leaflet's getting started guide if you encounter this kind of problem.

**Closed by PaulLeCam** 2016-06-09 19:51 UTC

**Comment by evenfrost** [comment] 2016-06-28 22:42
This seems to be an issue with webpack `style-loader`not operating well together with Leaflet as it loads styles after map initialization (see #46). Possible workaround is to set map container height with inline styles or use `invalidateSize()` method in `componentDidMount` handler, though this is not the option for functional React components.

**Comment by dopeboy** [comment] 2016-09-11 19:20
In case it helps anyone, I got this error because of the tiling service I was using (hydaa). Switching to mapbox resolved the issue for me.

**Comment by txs** [comment] 2017-07-20 15:30
I don't think it's a conf issue. I tried to load with css and the issue is still happening!

**Comment by Kibo007** [comment] 2018-06-07 09:45
best solution I found is to setTimeout. So problem is css modules are rendered after map it self and since leaflet depend on height it just renders first row since there is no in that moment css you set is you use css modules as well with webpack. So to go around that just set timeout with 0 miliseconds and it will be good. Code is here. Maybe this could be implemented in lib it self.

`import React, { Component } from 'react';
import { render } from 'react-dom';
import { Map, TileLayer } from 'react-leaflet';
import './mapView.scss';

class MapView extends Component {
  constructor() {
    super();
    this.state = {
      readyToRender: false,
    };
  }

  render() {
    const stamenTonerTiles =
      'http://stamen-tiles-{s}.a.ssl.fastly.net/toner-background/{z}/{x}/{y}.png';
    const stamenTonerAttr =
      'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>';
    const mapCenter = [39.9528, -75.1638];
    const zoomLevel = 12;

    setTimeout(() => {
      this.setState({ readyToRender: true });
    }, 0);

    return (
      <div>
        {this.state.readyToRender && (
          <Map center={mapCenter} zoom={zoomLevel}>
            <TileLayer attribution={stamenTonerAttr} url={stamenTonerTiles} />
          </Map>
        )}
      </div>
    );
  }
}

export default MapView;
`

**Comment by panuhorsmalahti** [comment] 2018-07-25 07:53
I also have this issue (latest React, webpack, css modules, leaflet and react-leaflet). My workaround is calling `invalidateSize`:

```
    componentDidMount() {
        setTimeout(() => {
            if (this.leafletMap.current) {
                this.leafletMap.current.leafletElement.invalidateSize();
            }
        }, 100);
    }
```

**Comment by rdgomt** [comment] 2019-03-06 13:15
Same here. I'm using the latest version of create-react-app. Seems to be something related, because I've never had this issue on other environments.

@FabulousAid how did you referenced map within componentDidUpdate?

**Comment by clementallen** [comment] 2019-03-06 13:22
@rdgomt interesting I've noticed the same using `react-scripts@2.1.4` and `react-scripts@2.1.5`.  I had to downgrade to `2.1.3` and the issue resolved.  If you downgrade to `2.1.3` does it fix it for you too?  Quite frustrating but not really sure where to start with fixing it...

**Comment by FabulousAid** [comment] 2019-03-06 13:25
> Same here. I'm using the latest version of create-react-app. Seems to be something related, because I've never had this issue on other environments.
> 
> @FabulousAid how did you referenced map within componentDidUpdate?

@rdgomt I used a ref to access the map's functions. I ended up doing this:

class MapView extends React.Component {
  mapRef = React.createRef();

  componentDidUpdate() {
    this.mapRef.current.leafletElement.invalidateSize();
  }

  render() {
    return (
      <Map
        ref={this.mapRef}
      />
    );
  }
}

**Comment by tribot91** [comment] 2019-07-12 11:00
It does not work for me. I already figured out that the problem is the center of map being top left of the leaflet which is why only small part of map loads. None of giving width/height, invalidating size, downgrading prop types and react scripts solved my problem yet.

**Comment by BarbaraSousas** [comment] 2019-12-30 02:08
My problem was solved setting the zoom

**Comment by citizen-dror** [comment] 2020-03-06 08:19
solution using hooks (and mobx sotre) in FunctionComponent :

parent tabs Component
```
interface IProps { 
    defaultKey? :string
}
export const TabsTemplate: React.FC<IProps> = observer(({defaultKey="charts"}) => {
    const [activeKey] = useState(defaultKey);
    const store = useStore();
    store.isReadyToRenderMap = false;
    return (
        <Tabs defaultActiveKey={activeKey} id="main-tabs"
            onSelect={(activeKey: any) => {
                if (activeKey === "map") {
                    //map is renderd only when tab is shown
                    store.isReadyToRenderMap = true;
                }
            }}
        >
            <Tab eventKey="charts" title={"Charts"}>
                <GroupByGraphsPanel />
            </Tab>
            <Tab eventKey="map" title={"Map"}>
                <MyMap />
            </Tab>
        </Tabs>
    )
})
```
child map Component
```
const MyMap : FunctionComponent<IProps> = observer(() => {
  const mapRef = useRef<any>();
  const store = useStore();
  const reactMapCenter = toJS(store.mapCenter);
  const WRAPPER_STYLES = { height: '500px', width: '100vw', maxWidth: '100%' };
  const didMountRef = useRef(false) 
  useEffect(() => {
    if (didMountRef.current) { 
      if (mapRef.current) {
        //mapRef.current  = true - like componentDidUpdate
        //this event is fierd when parent tab is shown - help render map 
        mapRef.current.leafletElement.invalidateSize(false);
      }
    } 
    else didMountRef.current = true
  })
  return (
    <div>
        <Map ref={mapRef}
          center={reactMapCenter}
          zoom={13}
          style={WRAPPER_STYLES}
        >
          <TileLayer
            attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
            url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          />
          <AccidentsMarkers />
        </Map>
        {store.isReadyToRenderMap?"":""}
    </div>
  )
})
```

**Comment by vtarelkin** [comment] 2021-08-18 16:33
everytime new map component receives new props (i.e. height) we need to revalidate size in useEffect, for ex.

`    const mapRef = useRef(null);
`

```
    useEffect(() => {
        mapRef.current.leafletElement.invalidateSize();
    }, [mapHeightStyle]);

```
