### ISSUE TITLE
L.Mixin is deprecated in Leaflet 1.0.0

### ISSUE THREAD

**Issue by jgravois** [PaulLeCam/react-leaflet#290] opened 2017-02-28 18:30 UTC
- [X] The issue has not already been reported.

hi there!

i'm logging this issue to notify you that `L.Evented.extend()` is the preferred technique in Leaflet 1.0.0 to specify mixins for objects that support events and should be used in favor of `L.Mixin`

more info: https://github.com/Leaflet/Leaflet/issues/5358

```js
class MapMock extends LeafletMock.Map {
  constructor(id, options = {}) {
    super();
    assign(this, L.Mixin.Events);
```
https://github.com/PaulLeCam/react-leaflet/blob/c5fb403b3ab5c2e0330f4311ffae192fc6955224/__mocks__/leaflet.js

**Comment by PaulLeCam** [comment] 2017-03-01 20:41
Hi!
Thanks for reporting this, should be fixed in latest commit, using `L.Evented`.

**Closed by PaulLeCam** 2017-03-01 20:41 UTC

**Comment by alterx** [comment] 2017-08-09 20:46
Hey @PaulLeCam , not sure if it's related but I'm seeing some warnings regarding
`Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead.`

Versions: 
"leaflet": "1.2.0"
"leaflet-routing-machine": "3.2.5"

**Comment by PaulLeCam** [comment] 2017-08-09 21:47
`L.Mixin` is not used anymore in this library, please check the behavior without any Leaflet plugin.

**Comment by alterx** [comment] 2017-08-09 22:30
You're right, the root cause is, indeed, inside the `leaflet-routing-machine` plugin. 
Thanks!
