### ISSUE TITLE
Error related to babel-loader in the create-react-app project

### ISSUE THREAD

**Issue by Khamidullaev** [PaulLeCam/react-leaflet#882] opened 2021-05-18 13:40 UTC
# Error related to babel-loader in the create-react-app project

I have a project created using create-react-app. Until recently, everything worked well with react-leaflet. But now, when compiling the project, it gives this error:

```sh
./node_modules/@react-leaflet/core/esm/path.js 10:41
Module parse failed: Unexpected token (10:41)
File was processed with these loaders:
 ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   useEffect(function updatePathOptions() {
|     if (props.pathOptions !== optionsRef.current) {
>       const options = props.pathOptions ?? {};
|       element.instance.setStyle(options);
|       optionsRef.current = options;
```

This operator (??) is supported in the project, but it throws an error in react-leaflet

**Comment by sonofjavascript** [comment] 2021-05-18 13:58
Similar problem related to code transpilation in  Chrome 73

```
layer.js:18 Uncaught (in promise) SyntaxError: Unexpected token ?
    at Object../node_modules/@react-leaflet/core/esm/layer.js
```

**Comment by nnatter** [comment] 2021-05-18 14:40
You might be able to fix this by using the `@babel/plugin-proposal-nullish-coalescing-operator` in your project. See https://github.com/PaulLeCam/react-leaflet/issues/883 for why this is happening.

**Comment by sonofjavascript** [comment] 2021-05-18 17:02
@nnatter if you are using the last version of the `@babel/preset-env` package there is no need to install the `@babel/plugin-proposal-nullish-coalescing-operator`. According to your post https://github.com/PaulLeCam/react-leaflet/issues/879#issuecomment-842239921, setting fixed version on those packages solves the issue.

Thanks

**Comment by nnatter** [comment] 2021-05-18 18:20
> According to your post [#879 (comment)](https://github.com/PaulLeCam/react-leaflet/issues/879#issuecomment-842239921), setting fixed version on those packages solves the issue.


This is not a solution. It is a workaround that prevents installing the `3.2.0` version of the package. The same error will pop up as soon as a new version of the package is released.

**Comment by dennisat** [comment] 2021-06-04 07:43
## Full solution for CRA without eject using the `customize-cra`

1. Add the customize-cra
`yarn add --dev customize-cra`
2. Create the `config-overrides.js` file are root folder with this content
```
const {
  override,
  addExternalBabelPlugins,
} = require("customize-cra");

module.exports = {
  webpack: override(
    ...addExternalBabelPlugins(
      "@babel/plugin-proposal-nullish-coalescing-operator"
    ),
  ),
};
```

**Comment by amaster507** [comment] 2021-06-18 15:41
> ## Full solution for CRA without eject using the `customize-cra`
> 1. Add the customize-cra
>    `yarn add --dev customize-cra`
> 2. Create the `config-overrides.js` file are root folder with this content
> 
> ```
> const {
>   override,
>   addExternalBabelPlugins,
> } = require("customize-cra");
> 
> module.exports = {
>   webpack: override(
>     ...addExternalBabelPlugins(
>       "@babel/plugin-proposal-nullish-coalescing-operator"
>     ),
>   ),
> };
> ```

This did not work for me. May be my inexperience with customize-cra but this exact code did not work for my app using cra.

**Comment by Some-banannas** [comment] 2021-08-19 01:56
I change the '??'  to  '||'   in all of the files that the error says and it seemed to work. Not sure if that solves the overall issue with babel but can help to get it working to now

**Comment by PaulLeCam** [comment] 2021-10-09 15:59
Duplicate of other closed issues.

**Closed by PaulLeCam** 2021-10-09 15:59 UTC

**Comment by morganney** [comment] 2021-10-10 13:35
@PaulLeCam you're not transpiling the nullish coalescing operator before publishing. Why?

**Comment by alfi-wes** [comment] 2021-10-21 18:57
link to closed issue?

**Comment by vyemialyanchyk** [comment] 2021-12-19 23:43
just because they like attention...

**Comment by worc** [comment] 2022-08-19 03:08
It's not really a duplicate if the bug was never resolved lol

**Comment by Andrew-Pynch** [comment] 2022-09-26 18:26
This still isn't working for me haha. What are we supposed to do to get a work around?
